### PR TITLE
CORS support for / and /cc

### PR DESCRIPTION
**Pull request by KrzysztofMadejski**
So Javascript widgets can parse whole API

Enables Access-Control-Origin-Allow for flask

It's already deployed on server

### CODE REVIEW

**Comment by KrzysztofMadejski** [comment]
+Generating statistics about gathered data: 

`mongo stats.js`
```
 ---- al_kuvendi ----
areas: 0 rows, source set in 0
events: 21 rows, source set in 21
logs: 628 rows, source set in 0
	finished.=311, running.=317, 
memberships: 747 rows, source set in 0
motions: 0 rows, source set in 0
organizations: 92 rows, source set in 0
	party.=11, parliamentary_group.=8, committee.=57, chamber.=8, =8, 
people: 223 rows, source set in 111
posts: 0 rows, source set in 0
speeches: 1664 rows, source set in 0
vote_events: 0 rows, source set in 0
votes: 0 rows, source set in 0

 ---- cz_psp ----
areas: 0 rows, source set in 0
events: 0 rows, source set in 0
logs: 0 rows, source set in 0
memberships: 0 rows, source set in 0
motions: 0 rows, source set in 0
organizations: 0 rows, source set in 0
people: 0 rows, source set in 0
posts: 0 rows, source set in 0
speeches: 0 rows, source set in 0
vote_events: 0 rows, source set in 0
votes: 0 rows, source set in 0

 ---- cz_senat ----
areas: 0 rows, source set in 0
events: 0 rows, source set in 0
logs: 0 rows, source set in 0
memberships: 0 rows, source set in 0
motions: 0 rows, source set in 0
organizations: 0 rows, source set in 0
people: 0 rows, source set in 0
posts: 0 rows, source set in 0
speeches: 0 rows, source set in 0
vote_events: 0 rows, source set in 0
votes: 0 rows, source set in 0

 ---- hu_orszaggyules ----
areas: 0 rows, source set in 0
events: 0 rows, source set in 0
logs: 8 rows, source set in 0
	failed.=1, finished.=7, 
memberships: 3564 rows, source set in 888
motions: 610 rows, source set in 610
organizations: 438 rows, source set in 428
	committee.=428, party.=9, chamber.=1, 
people: 244 rows, source set in 244
posts: 0 rows, source set in 0
speeches: 0 rows, source set in 0
vote_events: 23 rows, source set in 0
votes: 0 rows, source set in 0

 ---- kv_kuvendi ----
areas: 0 rows, source set in 0
events: 299 rows, source set in 299
logs: 0 rows, source set in 0
memberships: 1860 rows, source set in 0
motions: 326 rows, source set in 326
organizations: 98 rows, source set in 93
	party.=36, parliamentary_group.=40, committee.=17, chamber.=5, 
people: 1090 rows, source set in 602
posts: 0 rows, source set in 0
speeches: 45859 rows, source set in 0
vote_events: 326 rows, source set in 326
votes: 22137 rows, source set in 0

 ---- me_skupstina ----
areas: 0 rows, source set in 0
events: 0 rows, source set in 0
logs: 2 rows, source set in 0
	finished.=2, 
memberships: 284 rows, source set in 203
motions: 708 rows, source set in 708
organizations: 32 rows, source set in 21
	committee.=21, party.=10, chamber.=1, 
people: 81 rows, source set in 81
posts: 0 rows, source set in 0
speeches: 0 rows, source set in 0
vote_events: 0 rows, source set in 0
votes: 0 rows, source set in 0

 ---- pl_sejm ----
areas: 0 rows, source set in 0
events: 90 rows, source set in 90
logs: 6 rows, source set in 0
	failed.=5, finished.=1, 
memberships: 2354 rows, source set in 0
motions: 4704 rows, source set in 4704
organizations: 43 rows, source set in 33
	party.=9, committee.=33, chamber.=1, 
people: 504 rows, source set in 504
posts: 0 rows, source set in 0
speeches: 4638 rows, source set in 4638
vote_events: 0 rows, source set in 0
votes: 0 rows, source set in 0

 ---- pl_senat ----
areas: 0 rows, source set in 0
events: 0 rows, source set in 0
logs: 16 rows, source set in 0
	finished.=8, running.=8, 
memberships: 302 rows, source set in 0
motions: 0 rows, source set in 0
organizations: 15 rows, source set in 15
	klub.=7, chamber.=8, 
people: 105 rows, source set in 105
posts: 0 rows, source set in 0
speeches: 0 rows, source set in 0
vote_events: 0 rows, source set in 0
votes: 0 rows, source set in 0

 ---- rs_skupstina ----
areas: 0 rows, source set in 0
events: 277 rows, source set in 277
logs: 0 rows, source set in 0
memberships: 4597 rows, source set in 0
motions: 399 rows, source set in 399
organizations: 146 rows, source set in 16
	party.=21, parliamentary_group.=13, friendship_group.=74, delegation.=11, committee.=20, speaker.=1, deputy_speaker.=1, chamber.=5, 
people: 1025 rows, source set in 0
posts: 0 rows, source set in 0
speeches: 310 rows, source set in 0
vote_events: 369 rows, source set in 369
votes: 60853 rows, source set in 0

 ---- sk_nrsr ----
areas: 0 rows, source set in 0
events: 1769 rows, source set in 0
logs: 9 rows, source set in 0
	running.=1, finished.=8, 
memberships: 6319 rows, source set in 6319
motions: 29778 rows, source set in 29778
organizations: 265 rows, source set in 265
	friendship group.=95, delegation.=32, caucus.=37, committee.=95, chamber.=6, 
people: 771 rows, source set in 627
posts: 0 rows, source set in 0
speeches: 459962 rows, source set in 459962
vote_events: 29778 rows, source set in 29778
votes: 4437208 rows, source set in 0

 ---- xx_example ----
areas: 0 rows, source set in 0
events: 0 rows, source set in 0
logs: 0 rows, source set in 0
memberships: 0 rows, source set in 0
motions: 0 rows, source set in 0
organizations: 0 rows, source set in 0
people: 0 rows, source set in 0
posts: 0 rows, source set in 0
speeches: 0 rows, source set in 0
vote_events: 0 rows, source set in 0
votes: 0 rows, source set in 0
```

**Comment by girogiro** [comment]
Nice. Thanks!

**Comment by girogiro** [comment]
Moved all JS scripts to `/js` subdir.

**Comment by girogiro** [comment]
The stats show that we will need some code list for organization types.

**Pull request merged**
